module.exports = {
  
  docs :{
  'API Documentation': [

    {Objects : ['app.allFunctions', 
    'app.logger',
    'app.memory',
     'app.ai',
     'app.allSteps',
     'app.context',
     'app.contextEndTime',
     'app.createdUserMessageObject',
     'app.data',
     'app.dataStore',
     'app.entityValidators',
     'app.jsonWebToken',
     'app.libraryStartTime',
     'app.prediction',
     'app.predictionEndTime',
     'app.profile',
     'app.soap',
     'app.xmppObj',
     'app.xmlToJSON',
     'app.utilFunctions',
     'app.translate',
     'app.renderMessage',
     'app.phonetics']},
    
   {Methods: ['sendTextMessage' , 
              'executeFunction',
              'app.invokeJourney',
              'app.renderMessage',
              'virusScanningAPI',
              'updateTicketCsat',
              'getTicket',
              'updateTicketCustomFields',
              'libphonenumber-js',
              'getCurrentActiveTicket',
              'createEmailTicket',
              'getSupportSettings',
              'uploadWhatsappMedia',
              'sessionId',
              'messageId',
              'pageUrl',
              'raiseTicket',
              'agentsAvailable',
              'agentsOnline',
              'getAgents',
              'setVariables',
              'getProfile',
              'start',
              'logTimes',
              'app_ai',
              'memory.set',
              'deleteStep',
              'customeEntityRecognizer',
              'ask',
              'term',
              'wordToNumber',
              'sendEmailMessage',
              'regexValidator',
              'orchestratorBotId',
              'app.BOT_ENV',
              'triggerJourney',
              'isBotPaused',
              'extractName',
              'getVariable']},
    ],
    
    'Integrations' : [ 'WhatsAppAPI',
                       'Microsoft Teams',
                       'Slack'],
    
    'Release Notes' : [ 'Aug 2020',
                        'Sep 2020'],
  },
};
